### ISSUE TITLE
Force close android app

### ISSUE THREAD

**Issue by Nibb31** [nerzhul/ownCloud-SMS-App#149] opened 2017-05-03 07:59 UTC
The app force closes on login using application password.
  
### Steps to reproduce
1. In nextcloud: Application password > Create a new application password
2. On device: Launch app
3. Add an account. List of account types appears (why?)
4. Select Nextcloud SMS
5. Enter server URL, user and password (as generated in step 1).
6. Click Connect.

### Expected behaviour
App should connect to the server. Account should be created.

### Actual behaviour
App returns to Welcome screen
"Nextcloud SMS has stopped" message
Account is not created.

### Server configuration

Nextcloud: 11.0.3 (stable)
Phone Sync 1.11.5
Two Factor TOTP Provider 1.1.0

OpenMediaVault 3.xx (Linux Debian Jessie)
nginx version 1.6.2
HTTPS SSL certificate: Let's Encrypt

### Client configuration

Android: 6.0.1 (latest update)
Device: Samsung A5 (2017) SM-A520F
App version: Nextcloud SMS (fr.unix_experience.owncloud_sms) 1.0.0

### Logs

Report and logs submitted through Google Play Store

**Comment by nerzhul** [comment] 2017-05-03 13:32
Thanks for reporting through playstore.

here is the related stacktrace (i masked your instance URL)

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Invalid uri 'https://xxx.fr /index.php/apps/ocsms/get/apiversion?format=json': Invalid authority
	at org.apache.commons.httpclient.HttpMethodBase.<init>(HttpMethodBase.java:222)
	at org.apache.commons.httpclient.methods.GetMethod.<init>(GetMethod.java:89)
	at fr.unix_experience.owncloud_sms.engine.OCHttpClient.get(OCHttpClient.java:83)
	at fr.unix_experience.owncloud_sms.engine.OCHttpClient.getVersion(OCHttpClient.java:91)
	at fr.unix_experience.owncloud_sms.activities.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:263)
	at fr.unix_experience.owncloud_sms.activities.LoginActivity$UserLoginTask.doInBackground(LoginActivity.java:250)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by nerzhul** [comment] 2017-05-03 13:33
Oh ! it seems you added a space after FR in original URI  Can that be the cause ?
Please confirm, i also need to catch this specific error

**Comment by nerzhul** [comment] 2017-05-03 13:48
Crash is now fixed and proper error will be shown to user

**Comment by nerzhul** [comment] 2017-05-03 13:48
I will release 1.0.1 this evening

**Closed by nerzhul** 2017-05-03 13:48 UTC

**Comment by Nibb31** [comment] 2017-05-03 15:14
Hi,
You are correct. I use the Swiftkey keyboard and it seems like it appends a space when it auto-suggests strings. Removing the trailing space fixed it. Thanks for the update !

**Comment by nerzhul** [comment] 2017-05-03 15:16
No problem your stacktrace was very useful and permit to solve a blocking :)
