### ISSUE TITLE
Can't login with Android 7.1.1

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ownCloud-SMS-App#122] opened 2016-12-16 22:18 UTC
### Steps to reproduce
1. Download the Nextcloud server app
2. Download the phone app in Play Store
3. Try to login with correct credentials

### Expected behaviour
I should be able to login

### Actual behaviour
It says that I have the wrong password or username

### Server configuration

**Nextcloud version:** 
11
**PHP version:**
7.0
**HTTPd server:**
Apache 2.4
**HTTPS:**
Yes
### Client configuration
0.23.0
**Android version:**
7.1.1
**Phone:**
Nexus 5x
**Nextcloud SMS app version:**
1.9.0

**Comment by nerzhul** [comment] 2016-12-18 19:41
I didn't touch the login thing, related to nextcloud itself, but first, please ugprade server to 1.11.0 at least

**Comment by jajaX** [comment] 2016-12-19 00:11
Hi !

same problem with owncloud 9.1.3, ownCloud SMS  1.11.0 and Android ownCloud SMS 0.23 (from f-droid) under Android 7.1.1 (Cyanogemod 14.1)

=> connexion failed. are you sure it's a good server  ?

yes, i'm sure !

**Comment by Ecphrasis** [comment] 2016-12-19 09:04
Hi !

Same problem here, with nextcloud 11.0.0,  Nextcloud SMS 1.11.3, and Android owncloud SMS 0.23.0 (from Google play) under Android 6.0 (looks like it's not related to android 7).

**Comment by nerzhul** [comment] 2016-12-19 09:21
I have nextcloud 11.0, same tag, same android version... maybe it's related to new security politic ?

I'm using LDAP, what auth backend did you use ? Authentication is done by Nextcloud itself neither by ocsms server nor client, we are just sending credentials.

**Comment by nerzhul** [comment] 2016-12-19 09:31
Another question, is this a nextcloud or app first install ?

**Comment by Ecphrasis** [comment] 2016-12-19 10:06
I use couple login and password, it's an old nextcloud updated since the first release of nextcloud, in june I think :) I bought your app yesterday night, two days after update to nextcloud 11.0.0

**Comment by nerzhul** [comment] 2016-12-19 10:08
Okay, maybe i should look at application backend with no information stored using an emulator.

Do you have a logcat or something similar on your phone ? Could be good to have app logs

**Comment by Ecphrasis** [comment] 2016-12-19 10:09
I don't have logcat, but I can install one, if you tell me where is it ;)

**Comment by nerzhul** [comment] 2016-12-19 10:10
on the playstore you can download logcat application, and then you can view all your logs, then filter on this application

**Comment by Ecphrasis** [comment] 2016-12-19 10:20
I tried two apps, but I have no root permission. I can't read the others apps logs...

**Comment by Ecphrasis** [comment] 2016-12-19 10:30
I see the aborted connections in the panel admin logs : 

![log](https://cloud.githubusercontent.com/assets/11899009/21309339/4241ca84-c5de-11e6-906e-eedfb1f1303c.jpg)

and in the nextcloud.log : 

```
{"reqId":"DCfgEwubCe5e1Nf0kNBy","remoteAddr":"88.125.120.145","app":"admin_audit","message":"Login attempt: \"elodie\"","level":1,"time":"2016-12-19T11:26:47+01:00","method":"GET","url":"\/index.php\/ocs\/cloud\/user?format=json","user":"--","version":"11.0.0.10"}
{"reqId":"DCfgEwubCe5e1Nf0kNBy","remoteAddr":"88.125.120.145","app":"admin_audit","message":"Login successful: \"elodie\"","level":1,"time":"2016-12-19T11:26:47+01:00","method":"GET","url":"\/index.php\/ocs\/cloud\/user?format=json","user":"elodie","version":"11.0.0.10"}
{"reqId":"cUaSkbLiVJS5uyAQa5c7","remoteAddr":"88.125.120.145","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-12-19T11:26:48+01:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"--","version":"11.0.0.10"}
```

**Comment by enoch85** [comment] 2016-12-19 10:59
I installed the app for the first time on my current phone, FYI @nerzhul

**Comment by nerzhul** [comment] 2016-12-19 11:01
@Ecphrasis the last line is not related with our app, it's files app.
I think it's related to first installation... Something may be wrong in the first credential testing/save

**Comment by nerzhul** [comment] 2016-12-19 11:02
I will look to this bug very soon, This week i hope (it's Christmas, not easy to work)

**Comment by Ecphrasis** [comment] 2016-12-19 11:08
> the last line is not related with our app, it's files app.

Yes, but it appears each time I try to connect ;)
Every attempt to connect creates systematically these three lines...

**Comment by nerzhul** [comment] 2016-12-19 12:12
Can you give me apache/nginx access logs ?

**Comment by Ecphrasis** [comment] 2016-12-19 14:21
`88.125.120.145 - florian [19/Dec/2016:10:02:01 +0100] "GET /index.php/ocs/cloud/user?format=json HTTP/1.1" 302 4763 "-" "Android-ownCloud"`
`88.125.120.145 - - [19/Dec/2016:10:02:02 +0100] "GET /index.php/apps/files/ HTTP/1.1" 401 1381 "-" "Android-ownCloud"`

Every time, I have these two lines in the access.log.

**Comment by nerzhul** [comment] 2016-12-19 14:24
Okay, it seems /index.php/ocs/cloud/user?format=json redirect you to /index.php/apps/files/

**Comment by ezraholm50** [comment] 2016-12-19 19:14
Anyone has the 2 factor auth enabled?

**Comment by enoch85** [comment] 2016-12-19 20:30
Nope @ezraholm50

**Comment by nerzhul** [comment] 2016-12-20 18:24
Ok i can reproduce the problem with a fresh Android emulator using my own nextcloud 11

**Comment by nerzhul** [comment] 2016-12-20 18:24
Error is in the owncloud official library:

```
E/OwnCloudAuthenticator: *** status code: 401 ; response message: {"message":"Current user is not logged in"}
```

**Comment by nerzhul** [comment] 2016-12-20 19:48
I'm working on a fix but this will be longer than i think

**Comment by nerzhul** [comment] 2016-12-20 21:19
This is now fixed in master branch

**Closed by nerzhul** 2016-12-20 21:19 UTC
Labels: bug

**Comment by ShamimIslam** [comment] 2017-01-01 21:13
Do I need to upgrade my NextCloud 11 instance? Is this related to ownCloud android 2.2.0 from Google Play not being able to log into NextCloud 11?

Thanks.

**Comment by nerzhul** [comment] 2017-01-01 22:10
@ShamimIslam i don't think it's related, but the last release fix our issues

**Comment by ShamimIslam** [comment] 2017-01-01 22:58
Which release? 11.0 stable?

**Comment by ShamimIslam** [comment] 2017-01-02 00:27
Ok - what version of the android application should I be using to avoid the
problem? I downloaded form the play store.

**Comment by nerzhul** [comment] 2017-01-02 06:43
latest fixes the problems, else please open an issue with owncloud logs & android app logs

**Comment by ShamimIslam** [comment] 2017-01-02 06:46
Ok - no problem. I believe I have the latest client from Google Play.
