### ISSUE TITLE
Does not synchronize

### ISSUE THREAD

**Issue by freeeflyer** [nerzhul/ownCloud-SMS-App#153] opened 2017-06-29 12:44 UTC
### Steps to reproduce
1. Try to synchronize or wait for synchronization
2.
3.
### Notice
I have a LOT of SMSes

### Expected behaviour
All SMSes are synchronized and visible to webapp

### Actual behaviour
Not all SMSes are present on the web app

### Server configuration

**Nextcloud version: 12

**PHP version:7.0 (7.0.20-2~ubuntu14.04.1+deb.sury.org+1)

**Webserver: (Apache 2.4.7-1ubuntu4.16)

**HTTPS: yes (letsencrypt)

### Client configuration

**Android version: 6.0.1

**Phone: ZTE Axon 7 (A2017G)

**Nextcloud SMS app version: 1.1.0

### Logs

```
{"reqId":"5JNJMZ3Y6TRSsOBjiF6p","level":3,"time":"2017-06-28T07:04:23+00:00","remoteAddr":"77.136.14.98","user":"freeflyer","app":"PHP","method":"POST","url":"\/index.php\/apps\/ocsms\/push?format=json","message":"Invalid argument
 supplied for foreach() at \/var\/[...]\/apps\/ocsms\/db\/smsmapper.php#264","userAgent":"nextcloud-phonesync (1.1.0)","version":"12.0.0.29"}
```

## Screenshots

none..

**Comment by dh-connect** [comment] 2017-08-29 03:34
get the same error with nextcloud 12.0.2
Invalid argument supplied for foreach() at /data/ownclouddata/www/owncloud/apps/ocsms/db/smsmapper.php#264
Invalid argument supplied for foreach() at /data/ownclouddata/www/owncloud/apps/ocsms/controller/apicontroller.php#112

**Comment by nerzhul** [comment] 2017-08-29 05:55
@dh-connect your errors seems related to the \n issue due to json generation changes for performance in 1.2, here it's 1.1, the problem should be different

**Comment by dh-connect** [comment] 2017-08-29 11:38
here's what I tried:

I turned the json body scanner in modsecurity off, (SecRequestBodyAccess Off in modsecurity.conf): which removed the json error in apache error.log, sync still didn't work

I turned off modsecurity completely, sync still didn't work

I restored all messages on the phone with the android app (> 6000 messages); which worked great

I removed nc sms app from nextcloud, deleted the ocsms tables, removed appconfig settings, also converted the database from utf8 to utf8mb4 encoding

I reinstalled the latest nc sms app from the nextcloud store

I removed the android app from the phone, deleted the settings also, reinstalled the latest app on the phone from the android store, setup my cloud account 

Now I tried to backup the messages from the phone to the cloud, which didn't work, same error in nextcloud log, no error in apache error log

Is there anything else that I could try?

**Comment by nerzhul** [comment] 2017-08-29 11:50
@dh-connect it's sufficient for me, i need to verify the current json serializer in C++

**Comment by nerzhul** [comment] 2017-09-11 20:16
okay all should be fixed now, there were some problems with full sync model

**Comment by dh-connect** [comment] 2017-09-11 21:17
I tried it with the new app version 1.2.3, I tried to sync and it crashed after a few records, found 45 sms in table smsdata, now the app crashes each time when it tries to sync

**Comment by nerzhul** [comment] 2017-09-11 21:18
strange, i have synced 6500 sms without problem... can you provide me logcat logs ?

**Comment by dh-connect** [comment] 2017-09-11 21:42
[Log_2017-9-11_17-34-30.txt](https://github.com/nerzhul/ownCloud-SMS-App/files/1294158/Log_2017-9-11_17-34-30.txt)

here's the log

**Comment by nerzhul** [comment] 2017-09-11 21:44
Thanks, i see the problem, i will fix it asap it's caused by latest commit

**Comment by dh-connect** [comment] 2017-09-12 10:48
I tried it with version 1.2.4, app doesn't crash anymore and says sync complete after a while, but not a single sms in nexcloud app, smsdata table is empty, no error in apache log, nextcloud log:

Invalid argument supplied for foreach() at /data/ownclouddata/www/owncloud/apps/ocsms/db/smsmapper.php#264 |
Error | PHP | Invalid argument supplied for foreach() at /data/ownclouddata/www/owncloud/apps/ocsms/controller/apicontroller.php#112

I also try to reinstall the app, but no change

**Comment by nerzhul** [comment] 2017-09-12 11:39
it's very strange, are you able to dump the unencrypted HTTP communication ?

**Comment by dh-connect** [comment] 2017-09-12 11:54
no I blocked http on my server, i feel like the phone app is memorizing the last sync date somewhere, because now it says nothing to sync, although not a single sms has reached the server, where do you store the info?, i tried to clear app and cache data, still doesn't work

**Comment by nerzhul** [comment] 2017-09-12 12:04
you can reset cursor if you go (in app) to your account list, select your account and select reset sync cursor, it will resync all

**Comment by dh-connect** [comment] 2017-09-12 12:06
tried that too, doesn't work, then I get the sync completed and nothing was transfered

**Comment by dh-connect** [comment] 2017-09-12 12:13
here's the log

[Log_2017-9-12_08-08-43.txt](https://github.com/nerzhul/ownCloud-SMS-App/files/1295866/Log_2017-9-12_08-08-43.txt)

**Comment by nerzhul** [comment] 2017-09-12 14:13
It seems your phone do a single huge sync request, can you reduce the loop size in the app settings to a more little value ?

**Comment by dh-connect** [comment] 2017-09-12 15:18
yes this worked better, 4162 messages are in the database now, but I have more than 6000 messages on my phone, I noticed in the sms table that the id counted over 6000 but there are id's missing in between, it seems to me that the app has skipped messages during sync, taking the last id as the max minus the number of all records in the table: 2114 sms are still missing, any idea how to enforce a sync of all messages?

**Comment by dh-connect** [comment] 2017-09-13 11:44
Is there a way to find out why it's not syncing all messages, I have a copy of the old table, the missing sms are all in inbox, that's all I can tell

**Comment by nerzhul** [comment] 2017-09-13 11:48
it's nice to see reducing the cursor size permits to push correctly data, i think your server has a body limit it's why it was not synced. You can retry to reset cursor and relaunch a sync, but it's possible you have 2114 MMS and not SMS, and MMS are not synced atm as it's a little difficult to handle them properly

**Comment by dh-connect** [comment] 2017-09-13 11:57
no these are all SMS, they were synced before, limit size should be big enough (LimitRequestBody 2147483647), I reset the cursor several times, the number of synced messages remains the same, couldn't find something in logcat that looks like an error, any more ideas?

**Comment by nerzhul** [comment] 2017-09-13 11:59
do you have regular android app for your SMS or a specific app ?

**Comment by dh-connect** [comment] 2017-09-13 12:00
regular android app, is there a debug mode for your app which writes out a more detailed log?

**Comment by nerzhul** [comment] 2017-09-13 12:12
with logcat in verbose mode on app you have all, the message count shown is message number read from SMS database using regular Android API requests without specific filtering, maybe you have some SMS in non standard box ? can you find an app which browse the sms database easily to understand the problem ?

Another problem can be encoding problem server side are you using MySQL/MariaDB or pgsql ?

**Comment by dh-connect** [comment] 2017-09-13 14:12
I'm using MySQL and changed the encoding to UTF8 4 byte, when the app is counting the number of messages in logcat it shows them all, by the way I restored all the messages from the cloud with your app to the phone, deleted the oc sms tables, reinstalled the nextcloud app and when I tried to sync them back to the cloud it transferred not all of them, which means these messages were transferred before and worked so why wouldn't they work now, I also checked the messages which weren't transferred, but nothing unusual, message text length is also fine, I mean how does your logging work? If a message can't be transferred or doesn't make it into the cloud there should be an error, do you have some kind of feedback loop implemented which tells you what message actually made it to the cloud?

**Comment by nerzhul** [comment] 2017-09-13 14:21
the sync process generate a json object with a sms object list and send the bulk object to server. Server looks at the object, and if json is valid insert deserialized objects into database if they are not into database

**Comment by dh-connect** [comment] 2017-09-13 14:33
so the problem could be on the server, not inserting all sms from the json object, can we get more details from this process?

**Comment by nerzhul** [comment] 2017-09-13 14:35
for me, it's not some in the json object but one json object is refused sometimes by your server. php logs can help

**Comment by dh-connect** [comment] 2017-09-13 14:53
ok I will check what I can find on the server

**Comment by dh-connect** [comment] 2017-09-14 00:57
for some reason some of the packages are no arrays 
I inserted this test in checkPushStructure / apicontroller.php

if (is_array($smsDatas) || is_object($smsDatas))
                { ...  }
        else {
                $this->errorMsg = "Error: No SMS data array";
                return false;
             }
I get this error in a few cases
Where is smsDatas generated? Maybe I find out what happens.

**Comment by dh-connect** [comment] 2017-09-14 01:19
here's the log

[Log_2017-9-13_21-17-13.txt](https://github.com/nerzhul/ownCloud-SMS-App/files/1301416/Log_2017-9-13_21-17-13.txt)

**Comment by nerzhul** [comment] 2017-09-14 06:05
good job, can you add the test in ocsms app code https://github.com/nextcloud/ocsms it's important to have a such feedback.
smsDatas is generated by nextcloud itself, and if it's empty it's due to a problem in the query, but it's difficult to track it without dumping

**Comment by dh-connect** [comment] 2017-09-14 11:16
I used your new code, now I get the Error: smsCount field is NULL on my phone

**Comment by fyah** [comment] 2017-11-14 10:02
Hello,

I guess I have the same issue.
From the logs on the nexcloud side, I can see:

{"reqId":"lZBilGEB5KcuJb4V1N4A","level":3,"time":"2017-11-14T09:59:43+00:00","remoteAddr":"127.0.0.1","user":"xxxx","app":"PHP","method":"POST","url":"\/index.php\/apps\/ocsms\/push?format=json","message":"Invalid argument supplied for foreach() at \/volume1\/web\/owncloud\/apps\/ocsms\/controller\/apicontroller.php#112","userAgent":"nextcloud-phonesync (1.3.2)","version":"12.0.3.3"}
{"reqId":"lZBilGEB5KcuJb4V1N4A","level":3,"time":"2017-11-14T09:59:43+00:00","remoteAddr":"127.0.0.1","user":"xxxx","app":"PHP","method":"POST","url":"\/index.php\/apps\/ocsms\/push?format=json","message":"Invalid argument supplied for foreach() at \/volume1\/web\/owncloud\/apps\/ocsms\/db\/smsmapper.php#264","userAgent":"nextcloud-phonesync (1.3.2)","version":"12.0.3.3"}

I tried changing the number of sms to sync, no changes...

Any help appreciated.

**Comment by nerzhul** [comment] 2017-11-15 09:41
@fyah this bug is server side and should be fixed but currently it's hard to find where does it comes from as it's related to HTTP request routing in nextcloud

**Comment by fyah** [comment] 2017-11-15 13:17
ok thanks
So I'll disable sync for now, waiting for sms apps or nextcould update on the server side to retry

**Comment by nerzhul** [comment] 2017-11-15 16:27
the periodic sync is not very important, on receive sync is generally used, and network switching sync too

**Comment by fyah** [comment] 2017-11-16 08:12
I have all this enabled and still can't see my new sms being received on the server...
![screenshot_20171116-091122](https://user-images.githubusercontent.com/2546966/32880522-442d6742-caae-11e7-870a-6f9826388c4d.jpg)

**Comment by nerzhul** [comment] 2017-12-01 19:38
can you reduce bulk size from 2000 to 500 or lesser, sometimes the json message is very high

**Comment by jookk** [comment] 2017-12-01 21:28
on xiaomi says (there is nothing to sync). using Xiaomi sms app

**Comment by nerzhul** [comment] 2017-12-01 21:35
@jookk reset cursor in app account settings and launch a full sync

**Comment by OrpheeGT** [comment] 2017-12-03 18:23
Hello,
I have a similar issue...

Received SMS doesn't sync... when I manual sync "nothing to synchronize".
I reset cursor and sync works, but I must do it each time...

I have quite often sync issues in the notification bar when sync timing is enabled...

When I receive a SMS I can see the icon in the notification bar...

I can see the connexion in apache log :

`xx.xxx.xxx.xxx - Orphee [03/Dec/2017:19:19:30 +0100] "POST /nextcloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 4753 "-" "nextcloud-phonesync (1.3.3)"
xx.xxx.xxx.xxx - Orphee [03/Dec/2017:19:19:31 +0100] "POST /nextcloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 4757 "-" "nextcloud-phonesync (1.3.3)"
xx.xxx.xxx.xxx - Orphee [03/Dec/2017:19:19:36 +0100] "POST /nextcloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 4755 "-" "nextcloud-phonesync (1.3.3)"
xx.xxx.xxx.xxx - Orphee [03/Dec/2017:19:19:36 +0100] "POST /nextcloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 4753 "-" "nextcloud-phonesync (1.3.3)"
xx.xxx.xxx.xxx - Orphee [03/Dec/2017:19:19:46 +0100] "POST /nextcloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 4745 "-" "nextcloud-phonesync (1.3.3)"
xx.xxx.xxx.xxx - Orphee [03/Dec/2017:19:19:46 +0100] "POST /nextcloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 4747 "-" "nextcloud-phonesync (1.3.3)"`

But on my nextcloud, nothing synced.. Must force manually with a counter reset...

**Comment by nicolass67** [comment] 2017-12-06 08:57
Hello, 

I have the same issue with this configuration : 
Server : Debian stretch + nginx + php7.0-fpm (all rest of nextcloud working) 
Client : nextcloud SMS 1.3.2 official (buyed, NOT f-droid)

I made a http trace attached (file testnc.txt) 
[testnc.txt](https://github.com/nerzhul/ownCloud-SMS-App/files/1534424/testnc.txt)

In the nexcloud logs : Invalid argument supplied for foreach at ... smsmapper.php : 264

I tried to add some debug at smsmapper.php line 264 , with some printings or is_array($smsList) it answers "NULL". Maybe a clue for the smsList array variable. 

Regards, 

Nicolas.

**Comment by nicolass67** [comment] 2017-12-06 09:31
In fact I added this 2 lines where the errors happen : 
controller/apicontroller.php : 112 : 
error_log(is_array($smsDatas) ? 'smsDatas array ' : 'smsDatas not array' ); 
Quite same in db/smsmapper.php : 264 : 
error_log(is_array($smsList) ? 'smsList array ' : 'smsList not array' ); 

Result in php logs : 
[06-Dec-2017 09:25:13 UTC] smsDatas not array
[06-Dec-2017 09:25:13 UTC] smsList not array

So for some reason the input is not used as an array in the functions. 

I hope it can help, my PHP knowledge quite stops here.

**Comment by nerzhul** [comment] 2017-12-06 09:38
@nicolass67 can you use the following function ?

http://php.net/manual/fr/function.gettype.php

**Comment by nicolass67** [comment] 2017-12-06 09:59
Added this on both code blocks  : 
error_log('smsDatas is : '); 
error_log(gettype($smsDatas));

=> 
[06-Dec-2017 09:55:53 UTC] smsdatas not an array
[06-Dec-2017 09:55:53 UTC] smsDatas is :
[06-Dec-2017 09:55:53 UTC] NULL
[06-Dec-2017 09:55:53 UTC] smsList not an array
[06-Dec-2017 09:55:53 UTC] smsList is:
[06-Dec-2017 09:55:53 UTC] NULL

**Comment by nerzhul** [comment] 2017-12-06 10:00
NULL means the routing engine in nextcloud failed to deserialize the JSON, it's the problem, we need to understand where is the json deserialization problem to fix definitively this :(

**Comment by nicolass67** [comment] 2017-12-06 10:05
Could we "dump" the received JSON at the nextcloud level, then at the entrance of ocsms ? 
In the HTTP trace provided in my first post, it seems the json is quite OK (maybe you got tools to verify that).

**Comment by nerzhul** [comment] 2017-12-06 10:10
if you have server access and no SSL you can use tcpdump command

**Comment by nicolass67** [comment] 2017-12-06 10:12
It's with a tcpdump (anf httpparse) I produced the attached file testnc.txt :D

**Comment by nerzhul** [comment] 2017-12-06 11:05
it sounds good, except the date which seems very strange.
You never see all those messages in the database ?

**Comment by nicolass67** [comment] 2017-12-06 11:53
No when i dump the DB i can't find any related sms'es data. It fails before.

**Comment by nicolass67** [comment] 2017-12-06 12:59
I just saw there was a 12.0.4 version in stable branch of nextcloud. I made the update, problem stays alive. I already tried to go to beta 13.0 but ocms sin't yet compatible.

**Comment by nerzhul** [comment] 2017-12-07 07:24
ocsms app is relatively standalone in nextcloud, except it has to use nextcloud router & db interfaces. I think the problem is one message blocking the sync. Maybe you can try to take the HTTP stream and split it in multiple parts to find which part cause problem by replaying parts on your server. The json is relatively simple, smsCount + smsDatas (yeah typo) array of sms objects

**Comment by nicolass67** [comment] 2017-12-07 12:35
If you look at the HTTP trace , the exchange concerns 2 SMS it's simply the same sent to myself. 
The first : 

```
{
    "smsCount": 1,
    "smsDatas": [
        {
            "_id": 368,
            "address": "06 AA BB CC DD",
            "body": "Blabla",
            "date": 1.512457959539e+12,
            "mbox": 3,
            "read": "true",
            "seen": "true",
            "type": 2
        }
    ]
}
```
The data of the SMS is "Blabla" I dont think any of those characters are bad. 
The second : 
```
{
    "smsCount": 1,
    "smsDatas": [
        {
            "_id": 369,
            "address": "+336AABBCCDD",
            "body": "Blabla",
            "date": 1.512457962534e+12,
            "mbox": 3,
            "read": "false",
            "seen": "false",
            "type": 1
        }
    ]
}
```
Is it normal that the phone number is in a different form '+336xxxxx instead of 06' ? 
Is it possible to make nextcloud SMS compatible with nextcloud 13 maybe the routing engine is diffrent ? 
Is there no intermediate between ocsms and nextcloud (some Javascript frameworks or so) ? 

I'm not web developper my knowledge is quite limited but maybe we can add more debug somewhere .

Regards,

**Comment by nerzhul** [comment] 2017-12-07 12:46
no problem it's quite sufficient. The phone number is number reported by android itself without any alteration. Both sounds good.
I noted a huge refresh problem in the web application when doing my test (app is quite old and require some refactor/performance enhancements), did you check you have messages in database ?

Note: you have mbox = 3 which is an invalid mailbox. Do you use standard android message app ? If yes what is your android version (maybe something change in 8.0 in 8.1 if you use it)

**Comment by nicolass67** [comment] 2017-12-07 14:29
Nothing in database : 
```
sqlite3 owncloud.db .dump | grep ocsms | egrep -v 'CREATE' => 
INSERT INTO "oc_appconfig" VALUES('ocsms','installed_version','1.12.1');
INSERT INTO "oc_appconfig" VALUES('ocsms','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('ocsms','types','');
```
Same with a mysql DB

Note : I know for the mailbox id (we already discussed of it in mail :) ) My app  is SMS/MMS : 5.1.1-2237560 on Nexus 4 Android 5.1.1

**Comment by nerzhul** [comment] 2017-12-08 13:07
I should look at mailbox id = 3 on the server part which can be refused, either on client or on server

**Comment by nicolass67** [comment] 2017-12-08 20:08
@nerzhul : yes maybe, but it seems other users have the problem , not sure the sms they send are all mailbox id= 3. 

I did this test too : 

- create a test.json file containing : 
```
{
    "smsCount": 1,
    "smsDatas": [
        {
            "_id": 369,
            "address": "+336AABBCCDD",
            "body": "Blabla",
            "date": 1.512457962534e+12,
            "mbox": 3,
            "read": "false",
            "seen": "false",
            "type": 1
        }
    ]
}
```
(Of course i put a valid phone numer). 

- I send it :  
```
curl -X POST -u myuser -d @test.json http://mynextcloudhostname/index.php/apps/ocsms/push?format=json
Enter host password for user 'myuser'
{"status":true,"msg":"OK"}
```
That is the normal failing situation. 

- Now change the JSON to put a mailbox id = 0 (like received SMSes)
Same curl => same result, same error in nexcloud logs : 
`{"reqId":"0FfkygKUTs6OX7pI7RKN","level":3,"time":"2017-12-08T19:52:19+00:00","remoteAddr":"XXXX","user":"myuser","app":"PHP","method":"POST","url":"\/index.php\/apps\/ocsms\/push?format=json","message":"Invalid argument supplied for foreach() at \XXXXXX smsmapper.php#267","userAgent":"curl\/7.52.1","version":"12.0.3.3"}`

And nothing in the Database if I dump it 
Simple question what means the ""level":3" in the log of nextcloud ? 
Are the input SMS parsed in anyway by javascript or so ? (the is a js folder in ocms with angular and so)

I hope it can help. I really like this app , so I hope it works again, don't hesitate if you need tests. 

Nicolas

**Comment by OrpheeGT** [comment] 2017-12-10 18:58
Could you please tell why mbox 3 is an invalid mbox ?

I'm on mysql database, and I have sms_mailbox with value 3 for a lot of messages...

Should I wipe the database ?

**Comment by OrpheeGT** [comment] 2017-12-10 19:50
I wiped the database, made a reset and a synchro.
No sms_mailbox = 3 so it seemed to be good
I sent myself a SMS, not shown in nextcloud web interface.
In the database I see it, but in sms_mailbox = 3...

**Comment by nicolass67** [comment] 2017-12-14 20:06
Hello, 
It seems another topic talks about it : https://help.nextcloud.com/t/phonesync-app-ocsms-no-sync-then-no-connection-http-405/23301/2 => here problem happens in client 1.3.0

And a remark it seems that the problem appeared recently. As far As remember I could synchronize with nextcloud 12.0.3 (ocsms 1.12.1 ) until 13 november . I do my updates on the phone immediatly so the bug was probably introduced between 1 or 2 versions before this date. 

Regards,

**Comment by OrpheeGT** [comment] 2017-12-14 20:38
I uninstalled the latest 1.3.3 version and installed the old 1.2.5 SMS app version.
Same happens in the MySQL DB, sms_mailbox = 3 ... It seems to be a server side issue... I may be wrong but if I remember well, it was working before with this 1.2.5 version...

**Comment by nicolass67** [comment] 2017-12-24 10:25
Hello, 

I updtaed the android Nextcloud SMS offical to 1.3.4. problem still seems present. 

Regards, and merry Xmas !

**Comment by schiessle** [comment] 2018-01-03 19:29
I also have the problem that SMS are not synced. Like some of the other people here I use the f-droid version on a google free phone, not sure if this might be a issue.

I don't see the error messages described by the other people. What i found interesting is that by looking at the Apache access log I see that the android app connects regularly to the server, but I see always only this two GET requests:

````
"GET /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 200 4753 "-" "nextcloud-phonesync (1.3.4)"
GET /index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 200 1552 "-" "nextcloud-phonesync (1.3.4)"
````

There is never a POST request, so it seems like the Android app never tries to send new SMS's

**Comment by nicolass67** [comment] 2018-01-11 14:32
Hello, 

Just an update on this bug. 
My android client is still  : 1.3.4
I upgraded Nextcloud to 12.0.5 RC1 

Problem is still present. 
I put the nextcloud in debug level in my config.php : 
`'log_level => 0,
'debug' => true, 
'log_query' => true,
`
When the client make a request I can see some POST. But it seems it doesnt inset the SMS in the database 
`sqlite3 owncloud.db .dump | grep -i ocsms ` => doesnt show any sms datas inserted in base. 

Regards,

**Comment by chainsawbike** [comment] 2018-02-10 03:16
could it be related to this apache bug?

https://bz.apache.org/bugzilla/show_bug.cgi?id=53332

**Comment by nerzhul** [comment] 2018-02-10 09:07
@chainsawbike sounds to be an idea but some users don't use apache httpd

**Comment by nicolass67** [comment] 2018-02-10 14:17
@chainsawbike : I had same problem but using nginx. 
The problem is solved in this thread : [issue#217](https://github.com/nextcloud/ocsms/issues/217)
You need to comment the fastcgi_request_buffering off; that is in the nextcloud doc.

**Comment by nerzhul** [comment] 2018-02-10 14:57
@nicolass67 i add the notice to the readme, thanks

**Closed by nerzhul** 2018-02-10 14:57 UTC

**Comment by chainsawbike** [comment] 2018-02-10 20:02
if i understand correctly it is essentially the same issue with ngnix or Apache working with php-fpm

niginx has a work around by setting the request buffering to on allowing nginx to set the content-length header before passing over the fcgi protocol

apache does not do this, but there is an old patch

php-fpm does not believe it is their problem as they are following the fcgi spec ( https://bugs.php.net/bug.php?id=60826 )

so if my theory is correct the app sending the request is not setting the content length header  ( or setting it incorrectly ) and the most robust way to fix this issue is to set that header correctly.

**Comment by nicolass67** [comment] 2018-02-11 09:22
@chainsawbike : 
I tried these configuration : 

- nginx + php-fpm (no modification with doc of owncloud) -> fail 

- nginx proxy to  apache + mod_php -> OK

- apache + mod_php -> OK 

- apache + php-fpm -> fail 

So for nginx the workaround is the modifcation of the `proxy_request_buffering` setting
For apache + php-fpm maybe there is a similar option in apache.

**Comment by chainsawbike** [comment] 2018-02-11 21:53
Is the app setting the content length header? If not to me it seams the most robust solution to solve this issue as it should work regardless of the quirks of the specific web server and php implementation

I cannot find a way too get apache to add the header before passing to php-fpm other than the patch in this ( old ) apache bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=53332

**Comment by nerzhul** [comment] 2018-02-11 22:23
@chainsawbike it was the Android HTTP client, it should do it. Anyway version 2.0 used golang HTTP client which should solve those issues and also use HTTP/2.0
