### ISSUE TITLE
Honoring different SMS apps like Silence

### ISSUE THREAD

**Issue by ajna75** [nerzhul/ownCloud-SMS-App#112] opened 2016-11-01 16:51 UTC
Hi,

I just bought the app for over 1 Euro and unfortunately must see that the app is not honoring the standard sms app which is configured on my smartphone but takes only the sms app which comes preinstalled and which I don't use.
Please see into it, that other standard sms apps like e.g. Silence also synchronize with {Own|Next}cloud.

Thanks in advance.
Best regards, ajna

**Comment by nerzhul** [comment] 2016-11-01 20:43
Duplicate #106 

Note: standard SMS app is android app, not overriding android backend apps :)
If silence has a library to read its messages i'm okay for adding this

**Comment by ajna75** [comment] 2016-11-01 20:53
Silence app is open source. Fork it on github. Thanks for not just trying to make money but listening to the users, too.

Am 1. November 2016 21:43:56 MEZ, schrieb nerzhul <notifications@github.com>:
>Duplicate #106 
>
>Note: standard SMS app is android app, not overriding android backend
>apps :)
>If silence has a library to read its messages i'm okay for adding this
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nerzhul/ownCloud-SMS-App/issues/112#issuecomment-257689948

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by nerzhul** [comment] 2016-11-01 21:02
@ajna75 open source permits to do some money. the app only generate two days of paid work whereas i worked on it ~15 days...

**Comment by Bugsbane** [comment] 2016-12-30 16:37
This is marked as a duplicate of #106 however that bug seems to be about a connection problem, not anything about alternative SMS apps. I suspect that you meant that is a duplicate of #107 .

**Comment by nerzhul** [comment] 2016-12-30 16:39
exact @Bugsbane it's a typo fix

**Closed by nerzhul** 2016-12-30 16:39 UTC
Labels: duplicate
